dataset:
    option: 1
    max_len: 16
    max_num_lines: 20000

model:
    d_model: 64
    d_ff: 2048
    Nx: 6
    h: 8
    drop_p: 0

train:
    iters: 20
    batch_size: 1
    lr: 0.0001
    label_smooth: 0.1
    shuffle: True
    verbose: True
