dataset:
    option: 1
    max_len: 16
    max_num_lines: 20000

model:
    d_model: 64
    d_ff: 128
    Nx: 6
    h: 8
    drop_p: 0.1
    postLN: False

train:
    iters: 50
    batch_size: 64
    lr: 0.001
    label_smooth: 0
    shuffle: True
    verbose: True
